import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google'
import AuthContext from './context/AuthContext';
// import getCurrentUser from './actions/getCurentUser';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // const currentUser = await getCurrentUser()
  return (
    <html lang="ja">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
